name: Deploy to EC2

on:
  workflow_dispatch:  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        run: |
           echo "${{secrets.SSH_PRIVATE_KEY}}" > private_key.pem
           chmod 600 private_key.pem
           ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@3.109.5.203 << 'EOF'
    
            cd /home/ubuntu/thinkemr/Thinkmer-test
            git pull
            sudo docker-compose down
            sudo docker-compose up -d
           EOF
